### PR TITLE
Adds initial user profile fields and demo user accounts

### PR DESCRIPTION
**Pull request by grugnog**

### CODE REVIEW

**Comment by aravenrose** [comment]
@grugnog Looks like a couple modules might be missing...

`The import failed due for the following reasons:                                                                                                                [error]
Unable to install the <em class="placeholder">entity</em> module since it does not exist.
Unable to install the <em class="placeholder">profile</em> module since it does not exist.
`

**Comment by grugnog** [comment]
Shoot - the module missed my git add... I'll add that now.

**Comment by grugnog** [comment]
OK - module added

**Comment by aravenrose** [comment]
Good to go!

**Pull request merged**
